(()=>{if(window.__italkyHomeCleanup)return;window.__italkyHomeCleanup=true;const d=document;const style=d.createElement('style');style.textContent=`
.modernSearch,.filterRow,.homeBrandSeal{display:none!important}
.itTranslateWidget{margin:12px 20px 10px;height:72px;border:1px solid #cfe3f4;border-radius:22px;background:linear-gradient(135deg,#eef7ff,#e7f4ff);display:grid;grid-template-columns:1fr 54px 1fr;align-items:center;padding:8px 18px;box-shadow:0 7px 20px rgba(7,58,112,.07);cursor:pointer;user-select:none}
.itTranslateSide{display:flex;align-items:center;justify-content:center;gap:8px;font-weight:800;color:#0a2b4c;font-size:15px}.itTranslateFlag{font-size:28px;line-height:1}.itTranslateCenter{display:flex;flex-direction:column;align-items:center;justify-content:center;color:#0b5fa5;font-weight:900;font-size:11px;line-height:1.05}.itTranslateArrow{font-size:25px;line-height:1;margin-bottom:4px}.itTranslateWidget:active{transform:scale(.992)}
.panel{height:calc(100vh - 68px - 94px - 106px)!important;padding-bottom:24px!important}
.bottomNav{height:50px!important;bottom:56px!important;background:#fff!important;border-top:1px solid #dce8f2!important;padding:0!important;display:grid!important;grid-template-columns:repeat(3,1fr)!important}
.bottomNav button{height:50px!important;display:grid!important;place-items:center!important;background:#fff!important;color:#456176!important;font-size:14px!important;font-weight:800!important;letter-spacing:.01em!important;border:0!important}
.bottomNav .navIconWrap{display:none!important}.bottomNav button span:last-child{font-size:14px!important}.bottomNav button.active{color:#0a79d8!important;background:#eef7ff!important}
.itHomeFooter{position:absolute;left:0;right:0;bottom:0;height:56px;z-index:13;background:linear-gradient(135deg,#06182b,#0b3568);color:#dbeaf6;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;border-top:1px solid rgba(255,255,255,.08)}
.itHomeFooterLinks{display:flex;gap:15px;align-items:center;justify-content:center;line-height:1}.itHomeFooterLinks a{color:#e4f1fb;text-decoration:none;font-size:10px;font-weight:750}.itHomeSeal{font-size:8.5px;font-weight:800;opacity:.8;letter-spacing:.08px;line-height:1.05}.itHomeRune{font-family:"Segoe UI Historic","Noto Sans Old Turkic",serif;font-size:9px;margin-left:5px}
.fab{bottom:120px!important}
.waHead{height:64px!important;padding:6px 16px 5px!important}.waBrandLogo{width:92px!important;height:40px!important}.waActions{gap:12px!important}
@media(max-width:390px){.itTranslateWidget{margin-left:14px;margin-right:14px;padding-left:12px;padding-right:12px}.itTranslateFlag{font-size:25px}.itTranslateSide{font-size:14px}.itHomeFooterLinks{gap:12px}}
`;d.head.appendChild(style);
function mount(){const home=d.querySelector('.home');if(!home)return;d.querySelectorAll('.modernSearch,.filterRow,.homeBrandSeal').forEach(x=>x.remove());if(!home.querySelector('.itTranslateWidget')){const head=home.querySelector('.waHead');const w=d.createElement('button');w.type='button';w.className='itTranslateWidget';w.setAttribute('aria-label','Yakın çeviriyi aç');w.innerHTML='<div class="itTranslateSide"><span class="itTranslateFlag">🇹🇷</span><span>TR</span></div><div class="itTranslateCenter"><span class="itTranslateArrow">⇄</span><span>ÇEVİRİ</span></div><div class="itTranslateSide"><span>EN</span><span class="itTranslateFlag">🇬🇧</span></div>';w.addEventListener('click',()=>{location.href='/yeni_yuzyuze.html'});if(head)head.insertAdjacentElement('afterend',w);else home.prepend(w)}
const nav=home.querySelector('.bottomNav');if(nav){nav.querySelectorAll('.navIconWrap').forEach(x=>x.remove());nav.querySelectorAll('button').forEach(b=>{const spans=[...b.querySelectorAll('span')];if(spans.length>1)spans.slice(0,-1).forEach(x=>x.remove())})}
if(!home.querySelector('.itHomeFooter')){const f=d.createElement('footer');f.className='itHomeFooter';f.innerHTML='<div class="itHomeFooterLinks"><a href="/pages/about.html">Hakkımızda</a><a href="/pages/privacy.html">Gizlilik</a><a href="/pages/contact.html">İletişim</a></div><div class="itHomeSeal">italkyAI By Ozyigit\'s 2026 <span class="itHomeRune">𐰆𐰍𐰔 𐰇𐰔𐰘𐰃𐰏𐱅</span></div>';home.appendChild(f)} }
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',mount,{once:true});else mount();setTimeout(mount,250);setTimeout(mount,800);setTimeout(mount,1600);
})();