(()=>{
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const langMap={tr:'Türkçe',en:'English',de:'Deutsch',fr:'Français',es:'Español',it:'Italiano',ru:'Русский',ar:'العربية',fa:'فارسی',az:'Azərbaycanca',uz:'O‘zbekcha',kk:'Қазақша',ky:'Кыргызча',zh:'中文',ja:'日本語',ko:'한국어',pt:'Português',nl:'Nederlands',pl:'Polski',uk:'Українська',el:'Ελληνικά',bg:'Български',ro:'Română',sr:'Srpski',hr:'Hrvatski',bs:'Bosanski',sq:'Shqip',mk:'Македонски'};
let room='',chan=null,guestLang='',guestName='Misafir',SB=null,myId='host-'+Math.random().toString(36).slice(2);
const myLang=()=>localStorage.getItem('italky_test_lang_v4')||JSON.parse(localStorage.getItem('italky_test_profile_v4')||'{}').lang||'tr';
const myName=()=>JSON.parse(localStorage.getItem('italky_test_profile_v4')||'{}').name||'iTalky';
async function sb(){if(SB)return SB;const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2');SB=createClient('https://wtzsnywujksshcwvemgz.supabase.co','sb_publishable_85JlITD5FKjDvdf4JHU0Dg_eByJrKVo',{auth:{persistSession:false}});return SB}
async function translate(text,from,to){if(!text||!to||from===to)return text;try{const r=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,source:from,target:to,from_lang:from,to_lang:to})});const j=await r.json();return String(j.text||j.translation||j.translated||j.translatedText||text)}catch{return text}}
function style(){if($('#guestQrStyle'))return;const s=document.createElement('style');s.id='guestQrStyle';s.textContent=`
.guestQrBtn{border:0;background:transparent;color:#172033;width:34px;height:34px;display:grid;place-items:center;padding:0}.guestQrBtn svg{width:25px;height:25px;stroke:currentColor;fill:none;stroke-width:2}.guestLayer{position:absolute;inset:0;z-index:160;background:#fff;display:none;flex-direction:column}.guestLayer.show{display:flex}.guestTop{height:62px;flex:0 0 62px;background:linear-gradient(135deg,#071b3a,#0a2b57);color:#fff;display:flex;align-items:center;gap:10px;padding:0 12px}.guestTop button{border:0;background:transparent;color:#fff;font-size:30px;width:40px}.guestTop strong{font-size:18px}.guestQrBody{flex:1;overflow:auto;padding:28px 22px;text-align:center;background:#f8fbff}.guestQrCard{max-width:360px;margin:auto;background:#fff;border:1px solid #dbe6f1;border-radius:24px;padding:22px;box-shadow:0 14px 40px #0b2a5120}.guestQrCard h2{margin:4px 0 8px}.guestQrCard p{color:#64748b;font-size:14px;line-height:1.45}.guestQrCanvas{display:grid;place-items:center;min-height:230px}.guestStatus{margin-top:12px;color:#1687ff;font-weight:800}.guestChat{display:none;flex:1;min-height:0;flex-direction:column;background:#eaf1f8}.guestChat.show{display:flex}.guestMsgs{flex:1;overflow:auto;padding:14px 10px 90px}.gmsg{max-width:82%;padding:8px 10px;border-radius:10px;margin:5px 0;background:#fff;box-shadow:0 1px 1px #0001}.gmsg.mine{margin-left:auto;background:#cfe7ff}.gmeta{font-size:10px;color:#64748b;text-align:right;margin-top:3px}.guestComposer{display:flex;gap:7px;padding:8px;background:#dfe8f1}.guestComposer input{flex:1;min-width:0;height:46px;border:0;border-radius:24px;padding:0 16px;font-size:16px}.guestComposer button{width:46px;height:46px;border:0;border-radius:50%;background:#1687ff;color:#fff;font-size:20px}.guestLink{font-size:11px;word-break:break-all;color:#64748b;margin-top:8px}
`;document.head.appendChild(s)}
function inject(){style();const actions=$('.waActions');if(!actions||$('#guestQrBtn'))return;const b=document.createElement('button');b.id='guestQrBtn';b.className='guestQrBtn';b.title='Misafir QR';b.setAttribute('aria-label','Misafir QR');b.innerHTML='<svg viewBox="0 0 24 24"><path d="M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h3v3h-3zM18 14h3v3h-3zM14 18h3v3h-3zM18 18h3v3h-3z"/></svg>';actions.prepend(b);b.onclick=openGuest;
const layer=document.createElement('div');layer.id='guestLayer';layer.className='guestLayer';layer.innerHTML=`<div class="guestTop"><button id="guestClose">‹</button><strong>Misafir ile sohbet</strong></div><div id="guestQrBody" class="guestQrBody"><div class="guestQrCard"><h2>QR ile bağlan</h2><p>Karşıdaki kişi uygulama indirmeden QR'ı okutsun, dilini seçsin ve sohbete katılsın.</p><div id="guestQrCanvas" class="guestQrCanvas"></div><div id="guestStatus" class="guestStatus">QR hazırlanıyor…</div><div id="guestLink" class="guestLink"></div></div></div><div id="guestChat" class="guestChat"><div id="guestMsgs" class="guestMsgs"></div><div class="guestComposer"><input id="guestInput" placeholder="Mesaj"><button id="guestSend">➤</button></div></div>`;$('.app')?.appendChild(layer);$('#guestClose').onclick=closeGuest;$('#guestSend').onclick=sendHost;$('#guestInput').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sendHost()}}}
async function loadQr(text){const box=$('#guestQrCanvas');box.innerHTML='';if(!window.QRCode){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}new QRCode(box,{text,width:220,height:220,colorDark:'#071b3a',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M})}
async function openGuest(){inject();room=(crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)).replace(/-/g,'').slice(0,18);guestLang='';guestName='Misafir';$('#guestMsgs').innerHTML='';$('#guestChat').classList.remove('show');$('#guestQrBody').style.display='block';$('#guestLayer').classList.add('show');const url=`${location.origin}/pages/italky_guest.html?room=${encodeURIComponent(room)}&hostLang=${encodeURIComponent(myLang())}&hostName=${encodeURIComponent(myName())}`;$('#guestLink').textContent=url;$('#guestStatus').textContent='Misafirin bağlanması bekleniyor…';try{await loadQr(url)}catch{$('#guestQrCanvas').innerHTML='<p>QR oluşturulamadı. Bağlantıyı paylaşabilirsin.</p>'}const c=await sb();chan=c.channel('italky-guest-room:'+room);chan.on('broadcast',{event:'guest-join'},async({payload})=>{if(payload?.room!==room)return;guestLang=payload.lang||'en';guestName=payload.name||'Misafir';$('#guestStatus').textContent=`${guestName} bağlandı · ${langMap[guestLang]||guestLang}`;await chan.send({type:'broadcast',event:'host-ready',payload:{room,hostName:myName(),hostLang:myLang()}});setTimeout(()=>{$('#guestQrBody').style.display='none';$('#guestChat').classList.add('show')},350)});chan.on('broadcast',{event:'message'},({payload})=>{if(payload?.room!==room||payload?.sender===myId||payload?.side!=='guest')return;addMsg(false,payload.translated||payload.original||'',payload.original)});await chan.subscribe()}
function addMsg(mine,text,original){const d=document.createElement('div');d.className='gmsg'+(mine?' mine':'');d.innerHTML=`<div>${esc(text)}</div>${original&&original!==text?`<div style="font-size:11px;color:#64748b;margin-top:4px">${mine?'Karşı tarafta':'Orijinal'}: ${esc(original)}</div>`:''}<div class="gmeta">${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div>`;$('#guestMsgs').appendChild(d);$('#guestMsgs').scrollTop=$('#guestMsgs').scrollHeight}
async function sendHost(){const i=$('#guestInput'),text=i.value.trim();if(!text||!chan||!guestLang)return;i.value='';const translated=await translate(text,myLang(),guestLang);addMsg(true,text,translated);await chan.send({type:'broadcast',event:'message',payload:{room,sender:myId,side:'host',original:text,translated,fromLang:myLang(),toLang:guestLang}})}
async function closeGuest(){try{if(chan&&SB)await SB.removeChannel(chan)}catch{}chan=null;room='';$('#guestLayer')?.classList.remove('show')}
function boot(){inject();setTimeout(inject,600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();