(()=>{
const $=id=>document.getElementById(id);const q=s=>document.querySelector(s);const qa=s=>[...document.querySelectorAll(s)];
const toast=t=>{const s=$('status');if(s)s.textContent=t};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const phoneKey=()=>{try{return JSON.parse(localStorage.getItem('italky_test_profile_v4')||'{}').phone||localStorage.getItem('italky_test_phone_v4')||'guest'}catch{return'guest'}};
const callKey=()=>`italky_test_calls_v5_${String(phoneKey()).replace(/\D/g,'')}`;
function getCalls(){try{return JSON.parse(localStorage.getItem(callKey())||'[]')}catch{return[]}}
function addCall(type,name,number,status='Arandı'){const a=getCalls();a.unshift({type,name:name||number||'Bilinmeyen',number:number||'',status,at:Date.now()});localStorage.setItem(callKey(),JSON.stringify(a.slice(0,100)));renderCalls()}
function renderCalls(){const p=$('calls');if(!p)return;const a=getCalls();p.innerHTML=a.length?a.map(c=>`<button class="row callHistoryRow"><div class="avatar">${c.type==='video'?'▣':'☎'}</div><div class="rowBody"><div class="rowTop"><strong>${esc(c.name)}</strong><span class="time">${new Date(c.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></div><div class="sub">${c.status} · ${c.type==='video'?'Görüntülü':'Sesli'}${c.number?' · '+esc(c.number):''}</div></div></button>`).join(''):`<div class="empty"><h3>Henüz arama yok</h3><p>Sesli ve görüntülü aramalar burada görünecek.</p></div>`}
function currentPeer(){return {name:$('chatName')?.textContent||$('incomingName')?.textContent||'',number:$('incomingNo')?.textContent||''}}
function ensureOverlay(){if($('v5Overlay'))return;const d=document.createElement('div');d.id='v5Overlay';d.style.cssText='position:absolute;inset:0;z-index:80;background:#fff;display:none;flex-direction:column';d.innerHTML=`<div style="height:58px;background:#008069;color:white;display:flex;align-items:center;gap:8px;padding:0 10px"><button id="v5Back" class="svgBtn" aria-label="Geri">‹</button><input id="v5Search" placeholder="Ara…" style="flex:1;height:38px;border:0;border-radius:19px;padding:0 14px;outline:0"><button id="v5Close" class="svgBtn">×</button></div><div id="v5Results" style="overflow:auto;flex:1;background:white"></div>`;q('.app')?.appendChild(d);$('v5Back').onclick=$('v5Close').onclick=()=>d.style.display='none';$('v5Search').oninput=renderSearch}
function renderSearch(){const term=($('v5Search')?.value||'').toLocaleLowerCase('tr');const rows=qa('#chats .row,#contacts .row');const seen=new Set();const html=rows.map(r=>{const t=r.innerText.trim();if(!t||seen.has(t)||!t.toLocaleLowerCase('tr').includes(term))return'';seen.add(t);return `<div class="row"><div class="avatar">⌕</div><div class="rowBody"><div class="rowTop"><strong>${esc(t.split('\n')[0])}</strong></div><div class="sub">${esc(t.split('\n').slice(1).join(' · '))}</div></div></div>`}).join('');$('v5Results').innerHTML=html||'<div class="empty"><h3>Sonuç yok</h3></div>'}
function openSearch(){ensureOverlay();$('v5Overlay').style.display='flex';$('v5Search').value='';renderSearch();setTimeout(()=>$('v5Search').focus(),50)}
function ensureMenu(){if($('v5Menu'))return;const m=document.createElement('div');m.id='v5Menu';m.style.cssText='position:absolute;z-index:90;right:8px;top:54px;width:220px;background:white;border-radius:4px;box-shadow:0 4px 18px #0004;display:none;padding:6px 0;color:#111b21';m.innerHTML='<button data-v5="profile">Profil bilgileri</button><button data-v5="number">Telefon numaram</button><button data-v5="calls">Arama geçmişi</button><button data-v5="clear">Test verilerini temizle</button>';m.querySelectorAll('button').forEach(b=>b.style.cssText='width:100%;border:0;background:white;text-align:left;padding:13px 18px;font-size:15px');q('.app')?.appendChild(m);m.onclick=e=>{const a=e.target.closest('[data-v5]')?.dataset.v5;if(!a)return;m.style.display='none';if(a==='profile'){const p=JSON.parse(localStorage.getItem('italky_test_profile_v4')||'{}');alert(`Ad: ${p.name||'-'}\nTelefon: ${p.phone||'-'}\nDil: ${p.lang||'-'}`)}if(a==='number')alert(phoneKey());if(a==='calls'){q('[data-tab="calls"]')?.click()}if(a==='clear'&&confirm('Bu cihazdaki test mesajları, kişiler ve profil silinsin mi?')){Object.keys(localStorage).filter(k=>k.startsWith('italky_test_')).forEach(k=>localStorage.removeItem(k));location.reload()}}}
function toggleMenu(){ensureMenu();$('v5Menu').style.display=$('v5Menu').style.display==='block'?'none':'block'}
function emojiPicker(){let p=$('emojiPickerV5');if(!p){p=document.createElement('div');p.id='emojiPickerV5';p.style.cssText='position:absolute;left:10px;bottom:62px;z-index:70;background:white;border-radius:14px;box-shadow:0 3px 15px #0003;padding:10px;display:none;max-width:290px';p.innerHTML=['😀','😂','😍','🥰','😎','👍','🙏','❤️','🔥','👏','🎉','😢','😡','🤔','😉','😘','👌','💯'].map(x=>`<button style="border:0;background:white;font-size:25px;padding:6px">${x}</button>`).join('');q('.chat')?.appendChild(p);p.onclick=e=>{if(e.target.tagName!=='BUTTON')return;const i=$('msg');i.value+=e.target.textContent;i.dispatchEvent(new Event('input',{bubbles:true}));i.focus()}}p.style.display=p.style.display==='block'?'none':'block'}
function filePicker(capture=false){let f=$('v5File');if(!f){f=document.createElement('input');f.id='v5File';f.type='file';f.accept='image/*,video/*,audio/*,.pdf,.doc,.docx,.xls,.xlsx,.txt';f.style.display='none';document.body.appendChild(f);f.onchange=()=>{const file=f.files?.[0];if(!file)return;const i=$('msg');i.value=`${file.type.startsWith('image/')?'📷':file.type.startsWith('video/')?'🎥':'📎'} ${file.name}`;i.dispatchEvent(new Event('input',{bubbles:true}));toast('Dosya seçildi · göndermek için oka dokun');f.value=''}}f.capture=capture?'environment':'';f.click()}
function bindSkinButtons(){const acts=qa('.waActions .svgBtn');if(acts[0]&&!acts[0].dataset.bound){acts[0].dataset.bound='1';acts[0].onclick=openSearch}if(acts[1]&&!acts[1].dataset.bound){acts[1].dataset.bound='1';acts[1].onclick=toggleMenu}const mini=qa('.waInputShell .mini');if(mini[0]&&!mini[0].dataset.bound){mini[0].dataset.bound='1';mini[0].onclick=emojiPicker}if(mini[1]&&!mini[1].dataset.bound){mini[1].dataset.bound='1';mini[1].onclick=()=>filePicker(false)}if(mini[2]&&!mini[2].dataset.bound){mini[2].dataset.bound='1';mini[2].onclick=()=>filePicker(true)}const more=q('.moreChat');if(more&&!more.dataset.bound){more.dataset.bound='1';more.onclick=toggleMenu}}
function bindCalls(){const a=$('audio'),v=$('video'),ac=$('accept'),dc=$('decline'),h=$('hang'),mic=$('mic'),cam=$('cam');if(a&&!a.dataset.log){a.dataset.log='1';a.addEventListener('click',()=>{const p=currentPeer();addCall('audio',p.name,p.number,'Giden arama')},{capture:true})}if(v&&!v.dataset.log){v.dataset.log='1';v.addEventListener('click',()=>{const p=currentPeer();addCall('video',p.name,p.number,'Giden arama')},{capture:true})}if(ac&&!ac.dataset.log){ac.dataset.log='1';ac.addEventListener('click',()=>{const p=currentPeer();addCall($('incomingMode')?.textContent?.includes('Görüntülü')?'video':'audio',p.name,p.number,'Gelen arama · cevaplandı')},{capture:true})}if(dc&&!dc.dataset.log){dc.dataset.log='1';dc.addEventListener('click',()=>{const p=currentPeer();addCall($('incomingMode')?.textContent?.includes('Görüntülü')?'video':'audio',p.name,p.number,'Gelen arama · reddedildi')},{capture:true})}if(h&&!h.dataset.ui){h.dataset.ui='1';h.addEventListener('click',()=>toast('Arama sonlandırıldı'))}if(mic&&!mic.dataset.ui){mic.dataset.ui='1';mic.addEventListener('click',()=>{mic.classList.toggle('off');toast(mic.classList.contains('off')?'Mikrofon kapalı':'Mikrofon açık')})}if(cam&&!cam.dataset.ui){cam.dataset.ui='1';cam.addEventListener('click',()=>{cam.classList.toggle('off');toast(cam.classList.contains('off')?'Kamera kapalı':'Kamera açık')})}}
function init(){renderCalls();bindSkinButtons();bindCalls();const obs=new MutationObserver(()=>{bindSkinButtons();bindCalls()});obs.observe(document.body,{subtree:true,childList:true});document.addEventListener('click',e=>{if($('v5Menu')?.style.display==='block'&&!e.target.closest('#v5Menu')&&!e.target.closest('.waActions')&&!e.target.closest('.moreChat'))$('v5Menu').style.display='none'});toast('Hazır')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setTimeout(init,700);
})();