(()=>{
const $=id=>document.getElementById(id);const q=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const myPhone=()=>{try{return JSON.parse(localStorage.getItem('italky_test_profile_v4')||'{}').phone||localStorage.getItem('italky_test_phone_v4')||''}catch{return''}};
const digits=s=>String(s||'').replace(/\D/g,'');const mediaKey=(peer)=>`italky_test_media_v6_${digits(myPhone())}_${digits(peer)}`;
let activePhone='',sb=null,inbox=null;
function toast(t){if($('status'))$('status').textContent=t}
function getMedia(peer){try{return JSON.parse(localStorage.getItem(mediaKey(peer))||'[]')}catch{return[]}}
function saveMedia(peer,m){const a=getMedia(peer);if(a.some(x=>x.id===m.id))return;a.push(m);localStorage.setItem(mediaKey(peer),JSON.stringify(a.slice(-80)))}
function fileToDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=rej;r.onload=()=>res(r.result);r.readAsDataURL(file)})}
async function compressImage(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=rej;r.onload=()=>{const im=new Image();im.onerror=rej;im.onload=()=>{const max=960,scale=Math.min(1,max/Math.max(im.width,im.height)),w=Math.max(1,Math.round(im.width*scale)),h=Math.max(1,Math.round(im.height*scale));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);let q=.78,data=c.toDataURL('image/jpeg',q);while(data.length>190000&&q>.28){q-=.1;data=c.toDataURL('image/jpeg',q)}res(data)};im.src=r.result};r.readAsDataURL(file)})}
function mediaHTML(m){const time=new Date(m.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});let body='';if(m.kind==='image')body=`<img src="${m.data}" alt="${esc(m.name||'Fotoğraf')}" style="display:block;max-width:250px;max-height:320px;border-radius:7px;object-fit:cover">`;else if(m.kind==='audio')body=`<audio controls src="${m.data}" style="max-width:250px"></audio>`;else body=`<a download="${esc(m.name||'dosya')}" href="${m.data}" style="display:block;color:#027eb5;text-decoration:none;max-width:240px;overflow:hidden;text-overflow:ellipsis">📎 ${esc(m.name||'Dosya')}</a>`;return `<div class="bubble ${m.mine?'mine':'theirs'} v6media" data-media-id="${esc(m.id)}">${body}<div class="meta">${time}</div></div>`}
function renderMedia(){if(!activePhone)return;const box=$('messages');if(!box)return;box.querySelectorAll('.v6media').forEach(x=>x.remove());getMedia(activePhone).forEach(m=>box.insertAdjacentHTML('beforeend',mediaHTML(m)));box.scrollTop=box.scrollHeight}
async function initSupabase(){if(sb||!myPhone())return;const mod=await import('https://esm.sh/@supabase/supabase-js@2');sb=mod.createClient('https://wtzsnywujksshcwvemgz.supabase.co','sb_publishable_85JlITD5FKjDvdf4JHU0Dg_eByJrKVo',{auth:{persistSession:false}});inbox=sb.channel('test-phone-v4:'+digits(myPhone()));inbox.on('broadcast',{event:'media-v6'},({payload})=>{if(payload?.to!==myPhone()||!payload?.from)return;const m={id:payload.id,mine:false,kind:payload.kind,data:payload.data,name:payload.name||'',at:payload.at||Date.now()};saveMedia(payload.from,m);if(activePhone===payload.from)renderMedia();toast('Medya mesajı geldi')});await inbox.subscribe()}
async function sendMedia(file){if(!activePhone){toast('Önce bir sohbet aç');return}await initSupabase();let data,kind='file';if(file.type.startsWith('image/')){kind='image';data=await compressImage(file)}else if(file.type.startsWith('audio/')){kind='audio';if(file.size>140000){toast('Test modunda ses dosyası 140 KB’dan küçük olmalı');return}data=await fileToDataURL(file)}else{if(file.size>120000){toast('Test modunda dosya 120 KB’dan küçük olmalı');return}data=await fileToDataURL(file)}if(String(data).length>220000){toast('Dosya test aktarım sınırını aşıyor');return}const m={id:crypto.randomUUID?.()||Date.now()+Math.random().toString(36),mine:true,kind,data,name:file.name,at:Date.now()};saveMedia(activePhone,m);renderMedia();await sb.channel('test-phone-v4:'+digits(activePhone)).send({type:'broadcast',event:'media-v6',payload:{id:m.id,from:myPhone(),to:activePhone,kind,data,name:file.name,at:m.at}});toast('Medya gönderildi')}
function installPicker(){let f=$('v6File');if(!f){f=document.createElement('input');f.id='v6File';f.type='file';f.accept='image/*,audio/*,.pdf,.txt,.doc,.docx,.xls,.xlsx';f.style.display='none';document.body.appendChild(f);f.onchange=async()=>{const file=f.files?.[0];f.value='';if(file)try{await sendMedia(file)}catch(e){console.error(e);toast('Medya gönderilemedi')}}}return f}
function bindButtons(){const minis=[...document.querySelectorAll('.waInputShell .mini')];if(minis[1]&&!minis[1].dataset.mediaV6){minis[1].dataset.mediaV6='1';minis[1].onclick=e=>{e.stopPropagation();const f=installPicker();f.removeAttribute('capture');f.click()}}if(minis[2]&&!minis[2].dataset.mediaV6){minis[2].dataset.mediaV6='1';minis[2].onclick=e=>{e.stopPropagation();const f=installPicker();f.accept='image/*';f.setAttribute('capture','environment');f.click()}}}
function watchActive(){document.addEventListener('click',e=>{const r=e.target.closest('[data-phone]');if(r?.dataset.phone){activePhone=r.dataset.phone;setTimeout(renderMedia,150)}});const back=$('backChat');if(back&&!back.dataset.mediaV6){back.dataset.mediaV6='1';back.addEventListener('click',()=>{activePhone=''})}}
function init(){watchActive();bindButtons();initSupabase();const o=new MutationObserver(()=>{bindButtons();if(activePhone&&q('.chat')&&!q('.chat').classList.contains('hidden'))renderMedia()});o.observe(document.body,{subtree:true,childList:true});setTimeout(bindButtons,700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();