import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { BASE_DOMAIN } from '/js/config.js';
import { LANGUAGE_REGISTRY_129 } from '/js/language_registry_129.js';
const sb=createClient('https://wtzsnywujksshcwvemgz.supabase.co','sb_publishable_85JlITD5FKjDvdf4JHU0Dg_eByJrKVo',{auth:{persistSession:false}});
const $=id=>document.getElementById(id), digits=s=>String(s||'').replace(/\D/g,''), key=s=>digits(s), norm=s=>{const d=digits(s);return d?`+${d}`:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uuid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const initials=s=>String(s||'IT').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
const status=t=>{$('status').textContent=t};
const langName=c=>LANGUAGE_REGISTRY_129.find(x=>x.code===c)?.name||(c==='auto'?'Dil alınıyor…':c||'Dil alınıyor…');
const fmt=s=>{const d=digits(s);if(d.startsWith('90')&&d.length===12)return `+90 ${d.slice(2,5)} ${d.slice(5,8)} ${d.slice(8,10)} ${d.slice(10,12)}`;return s||''};
const flag=iso=>iso.toUpperCase().replace(/./g,c=>String.fromCodePoint(127397+c.charCodeAt()));
const fallback=[['tr','Türkiye','90'],['us','Amerika Birleşik Devletleri','1'],['gb','Birleşik Krallık','44'],['de','Almanya','49'],['fr','Fransa','33'],['it','İtalya','39'],['es','İspanya','34'],['nl','Hollanda','31'],['be','Belçika','32'],['at','Avusturya','43'],['ch','İsviçre','41'],['se','İsveç','46'],['no','Norveç','47'],['dk','Danimarka','45'],['fi','Finlandiya','358'],['pl','Polonya','48'],['cz','Çekya','420'],['gr','Yunanistan','30'],['bg','Bulgaristan','359'],['ro','Romanya','40'],['hu','Macaristan','36'],['rs','Sırbistan','381'],['ba','Bosna Hersek','387'],['hr','Hırvatistan','385'],['al','Arnavutluk','355'],['mk','Kuzey Makedonya','389'],['me','Karadağ','382'],['xk','Kosova','383'],['ge','Gürcistan','995'],['az','Azerbaycan','994'],['ru','Rusya','7'],['ua','Ukrayna','380'],['kz','Kazakistan','7'],['uz','Özbekistan','998'],['ae','Birleşik Arap Emirlikleri','971'],['sa','Suudi Arabistan','966'],['qa','Katar','974'],['kw','Kuveyt','965'],['il','İsrail','972'],['eg','Mısır','20'],['ma','Fas','212'],['dz','Cezayir','213'],['tn','Tunus','216'],['za','Güney Afrika','27'],['in','Hindistan','91'],['pk','Pakistan','92'],['bd','Bangladeş','880'],['cn','Çin','86'],['jp','Japonya','81'],['kr','Güney Kore','82'],['id','Endonezya','62'],['my','Malezya','60'],['sg','Singapur','65'],['th','Tayland','66'],['vn','Vietnam','84'],['ph','Filipinler','63'],['au','Avustralya','61'],['nz','Yeni Zelanda','64'],['ca','Kanada','1'],['mx','Meksika','52'],['br','Brezilya','55'],['ar','Arjantin','54'],['cl','Şili','56'],['co','Kolombiya','57'],['pe','Peru','51']].map(([iso,name,dial])=>({iso,name,dial}));
function countries(){const raw=window.intlTelInputGlobals?.getCountryData?.()||[];if(raw.length){let names;try{names=new Intl.DisplayNames(['tr'],{type:'region'})}catch{}return raw.map(x=>({iso:x.iso2,dial:x.dialCode,name:names?.of(x.iso2.toUpperCase())||x.name})).filter(x=>x.dial).sort((a,b)=>a.name.localeCompare(b.name,'tr'))}return fallback}
const countryList=countries();
function fillCountries(){const html=countryList.map(c=>`<option value="${c.iso}" data-dial="${c.dial}">${flag(c.iso)} ${esc(c.name)}  +${c.dial}</option>`).join('');$('country').innerHTML=html;$('contactCountry').innerHTML=html;$('country').value='tr';$('contactCountry').value='tr';paintCountry('country','dialCode','phone');paintCountry('contactCountry','contactDialCode','contactPhone')}
function fillLanguages(){const html=LANGUAGE_REGISTRY_129.filter(x=>x.online!==false).map(x=>`<option value="${x.code}">${esc(x.flag||'🌐')} ${esc(x.name)}</option>`).join('');$('myLang').innerHTML=html;$('myLang').value=myLang||'tr'}
function selectedCountry(id){const s=$(id),o=s.options[s.selectedIndex];return countryList.find(c=>c.iso===s.value)||{dial:o?.dataset?.dial||'',iso:s.value}}
function paintCountry(sid,did,iid){const c=selectedCountry(sid);$(did).textContent='+'+c.dial;$(iid).placeholder=c.iso==='tr'?'532 123 45 67':c.iso==='us'||c.iso==='ca'?'555 123 4567':'Telefon numarası'}
function phoneValue(sid,iid){const c=selectedCountry(sid);let local=digits($(iid).value);if(local.startsWith('00'))return norm(local.slice(2));if(local.startsWith('0'))local=local.replace(/^0+/,'');return norm(c.dial+local)}
let myNo=localStorage.getItem('italky_test_phone_v4')||'',myLang=localStorage.getItem('italky_test_lang_v4')||'tr',myProfile=JSON.parse(localStorage.getItem('italky_test_profile_v4')||'null'),pending='',pendingPhoto='';
let contacts=JSON.parse(localStorage.getItem('italky_test_contacts_v4')||'[]');let active=null,inbox=null,callChan=null,pc=null,stream=null,callState=null,incoming=null,rec=null,captionRec=null;
function persist(){localStorage.setItem('italky_test_contacts_v4',JSON.stringify(contacts))}
function avatarHTML(p,cls='avatar'){return p?.photo?`<div class="${cls}"><img src="${esc(p.photo)}"></div>`:`<div class="${cls}">${esc(initials(p?.name||p?.phone||'IT'))}</div>`}
function setAvatar(el,p){el.innerHTML=p?.photo?`<img src="${esc(p.photo)}">`:esc(initials(p?.name||p?.phone||'IT'))}
function upsertProfile(p){if(!p?.from)return;let i=contacts.findIndex(c=>c.phone===p.from);if(i<0){contacts.unshift({name:p.name||fmt(p.from),phone:p.from,lang:p.lang||'auto',photo:p.photo||''});i=0}else contacts[i]={...contacts[i],name:p.name||contacts[i].name,photo:p.photo||contacts[i].photo||'',lang:p.lang||contacts[i].lang||'auto'};persist();if(active?.phone===p.from)active=contacts[i];render();if(active?.phone===p.from)openChat(false)}
async function requestProfile(phone){await sb.channel('test-phone-v4:'+key(phone)).send({type:'broadcast',event:'profile-request',payload:{from:myNo,to:phone}})}
async function replyProfile(to){if(!myProfile)return;await sb.channel('test-phone-v4:'+key(to)).send({type:'broadcast',event:'profile-response',payload:{from:myNo,to,name:myProfile.name,photo:myProfile.photo||'',lang:myLang}})}
function showPhone(){$('verify').classList.remove('hidden');$('home').classList.add('hidden');$('phoneStep').classList.remove('hidden');$('otpStep').classList.add('hidden');$('profileStep').classList.add('hidden')}
function showProfile(){$('phoneStep').classList.add('hidden');$('otpStep').classList.add('hidden');$('profileStep').classList.remove('hidden');$('profileName').focus();status('Profilini tamamla')}
function showHome(){$('verify').classList.add('hidden');$('home').classList.remove('hidden');render();subscribeInbox()}
async function subscribeInbox(){if(!myNo)return;if(inbox)try{await sb.removeChannel(inbox)}catch{}inbox=sb.channel('test-phone-v4:'+key(myNo));inbox.on('broadcast',{event:'profile-request'},({payload})=>{if(payload?.to===myNo)replyProfile(payload.from)});inbox.on('broadcast',{event:'profile-response'},({payload})=>{if(payload?.to===myNo)upsertProfile(payload)});inbox.on('broadcast',{event:'message'},({payload})=>{if(payload?.to!==myNo)return;upsertProfile({from:payload.from,name:payload.senderName,photo:payload.senderPhoto,lang:payload.fromLang});saveMsg(payload.from,{mine:false,original:payload.original||'',translated:payload.translated||payload.original||'',at:Date.now(),voice:!!payload.voice});if(active?.phone===payload.from)renderMessages();render()});inbox.on('broadcast',{event:'ring'},({payload})=>{if(payload?.to!==myNo||callState)return;incoming=payload;upsertProfile({from:payload.from,name:payload.senderName,photo:payload.senderPhoto,lang:payload.fromLang});const p=contacts.find(c=>c.phone===payload.from)||{name:payload.senderName||fmt(payload.from),photo:payload.senderPhoto||'',phone:payload.from,lang:payload.fromLang||'auto'};$('incomingName').textContent=p.name;$('incomingNo').textContent=fmt(payload.from);$('incomingMode').textContent=payload.mode==='video'?'Görüntülü arama':'Sesli arama';setAvatar($('incomingAvatar'),p);$('incoming').classList.remove('hidden')});inbox.on('broadcast',{event:'accept'},async({payload})=>{if(callState&&payload.id===callState.id){await joinCall();await offer()}});inbox.on('broadcast',{event:'decline'},({payload})=>{if(callState&&payload.id===callState.id){status('Arama reddedildi');endCall()}});await inbox.subscribe();status('Hazır')}
function msgKey(p){return 'italky_test_msgs_v4_'+key(myNo)+'_'+key(p)}function getMsgs(p){return JSON.parse(localStorage.getItem(msgKey(p))||'[]')}function saveMsg(p,m){const a=getMsgs(p);a.push(m);localStorage.setItem(msgKey(p),JSON.stringify(a.slice(-300)))}
async function translate(text,from,to){if(!text||!to||to==='auto'||from===to)return text;const base=String(BASE_DOMAIN||'').replace(/\/+$/,'');try{const r=await fetch(base+'/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,source:from,target:to,from_lang:from,to_lang:to})});const j=await r.json();return String(j.text||j.translation||j.translated||j.translatedText||text)}catch{return text}}
async function sendText(text,voice=false){if(!active||!text.trim())return;const target=active.lang;if(!target||target==='auto'){status('Karşı tarafın dili alınıyor…');await requestProfile(active.phone);return}const original=text.trim();status('Çevriliyor…');const translated=await translate(original,myLang,target);saveMsg(active.phone,{mine:true,original,translated,at:Date.now(),voice});renderMessages();await sb.channel('test-phone-v4:'+key(active.phone)).send({type:'broadcast',event:'message',payload:{from:myNo,to:active.phone,original,translated,voice,fromLang:myLang,toLang:target,senderName:myProfile?.name||'',senderPhoto:myProfile?.photo||''}});status('Gönderildi');render()}
function renderMessages(){if(!active)return;const a=getMsgs(active.phone);$('messages').innerHTML=a.map(m=>`<div class="bubble ${m.mine?'mine':'theirs'}"><div>${m.voice?'🎙️ ':''}${esc(m.mine?m.original:m.translated)}</div>${m.mine&&m.original!==m.translated?`<div class="translated">Karşı tarafta: ${esc(m.translated)}</div>`:''}<div class="meta">${new Date(m.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div></div>`).join('');$('messages').scrollTop=$('messages').scrollHeight}
function openChat(show=true){if(!active)return;if(show)$('chat').classList.remove('hidden');$('chatName').textContent=active.name||fmt(active.phone);$('chatLang').textContent=active.lang&&active.lang!=='auto'?`${langName(active.lang)} · otomatik çeviri`:'Profil dili alınıyor…';setAvatar($('chatAvatar'),active);renderMessages();if(!active.lang||active.lang==='auto')requestProfile(active.phone)}
function render(){const make=c=>{const m=getMsgs(c.phone).at(-1);return `<button class="row" data-phone="${esc(c.phone)}">${avatarHTML(c)}<div class="rowBody"><div class="rowTop"><strong>${esc(c.name||fmt(c.phone))}</strong><span class="time">${m?new Date(m.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):''}</span></div><div class="sub">${m?esc(m.mine?m.original:m.translated):`${esc(fmt(c.phone))}${c.lang&&c.lang!=='auto'?' · '+esc(langName(c.lang)):''}`}</div></div></button>`};$('chats').innerHTML=contacts.length?contacts.map(make).join(''):`<div class="empty"><h3>Henüz sohbet yok</h3><p>Sağ alttaki düğmeden kişi ekle.</p></div>`;$('contacts').innerHTML=contacts.length?contacts.map(make).join(''):`<div class="empty"><h3>Kişi yok</h3><p>Telefon numarasıyla kişi ekle.</p></div>`}
$('country').onchange=()=>paintCountry('country','dialCode','phone');$('contactCountry').onchange=()=>paintCountry('contactCountry','contactDialCode','contactPhone');
$('sendBtn').onclick=()=>{const n=phoneValue('country','phone');if(!/^\+[1-9]\d{7,14}$/.test(n)){status('Geçerli telefon numarası gir');return}pending=n;myLang=$('myLang').value||'tr';$('phoneStep').classList.add('hidden');$('otpStep').classList.remove('hidden');$('verifyNumber').textContent=fmt(n);$('otp').focus();status('SMS gönderildi · Test kodu 123456')};
$('verifyBtn').onclick=()=>{if(digits($('otp').value)!=='123456'){status('Kod hatalı · 123456');return}showProfile()};$('editBtn').onclick=()=>{pending='';$('otp').value='';showPhone()};$('otp').oninput=e=>e.target.value=digits(e.target.value).slice(0,6);
$('photoPick').onclick=()=>$('profilePhotoInput').click();$('profilePhotoInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;pendingPhoto=await resize(f);$('profilePhoto').innerHTML=`<img src="${pendingPhoto}">`;$('profilePhoto').classList.remove('hidden');$('photoPh').classList.add('hidden')};function resize(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onerror=rej;fr.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement('canvas'),s=180;c.width=c.height=s;const x=c.getContext('2d'),q=Math.min(im.width,im.height),sx=(im.width-q)/2,sy=(im.height-q)/2;x.drawImage(im,sx,sy,q,q,0,0,s,s);res(c.toDataURL('image/jpeg',.72))};im.src=fr.result};fr.readAsDataURL(file)})}
$('saveProfile').onclick=()=>{const name=$('profileName').value.trim();if(!name){status('Görünen adını yaz');return}myNo=pending;myProfile={name,photo:pendingPhoto||'',phone:myNo,lang:myLang};localStorage.setItem('italky_test_phone_v4',myNo);localStorage.setItem('italky_test_lang_v4',myLang);localStorage.setItem('italky_test_profile_v4',JSON.stringify(myProfile));showHome()};
$('add').onclick=()=>{$('addSheet').classList.remove('hidden')};$('closeAdd').onclick=()=>$('addSheet').classList.add('hidden');$('saveContact').onclick=async()=>{const p=phoneValue('contactCountry','contactPhone');if(!/^\+[1-9]\d{7,14}$/.test(p)){status('Geçerli kişi numarası gir');return}if(p===myNo){status('Kendi numaranı ekleyemezsin');return}contacts=contacts.filter(x=>x.phone!==p);contacts.unshift({name:fmt(p),phone:p,lang:'auto',photo:''});persist();$('addSheet').classList.add('hidden');$('contactPhone').value='';render();status('Kişi eklendi · profili alınıyor');await requestProfile(p)};
$('backChat').onclick=()=>{$('chat').classList.add('hidden');active=null};$('send').onclick=()=>{const v=$('msg').value;$('msg').value='';sendText(v)};$('msg').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();$('send').click()}};
$('voice').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){status('Bu tarayıcı sesli mesajı yazıya çevirmeyi desteklemiyor');return}if(rec){try{rec.stop()}catch{}return}rec=new SR();rec.lang=myLang;rec.interimResults=false;rec.continuous=false;status('Konuş…');rec.onresult=e=>{const t=e.results?.[0]?.[0]?.transcript||'';if(t)sendText(t,true)};rec.onend=()=>rec=null;rec.onerror=()=>{rec=null;status('Ses alınamadı')};rec.start()};
document.addEventListener('click',e=>{const r=e.target.closest('[data-phone]');if(r){active=contacts.find(x=>x.phone===r.dataset.phone);if(active)openChat()}const t=e.target.closest('[data-tab]');if(t){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===t));['chats','contacts','calls'].forEach(id=>$(id).classList.toggle('hidden',id!==t.dataset.tab))}});
async function ring(mode){if(!active)return;if(!active.lang||active.lang==='auto'){status('Karşı tarafın profili alınıyor…');await requestProfile(active.phone);return}callState={id:uuid(),role:'caller',peer:active.phone,mode};showCall(mode);await sb.channel('test-phone-v4:'+key(active.phone)).send({type:'broadcast',event:'ring',payload:{id:callState.id,from:myNo,to:active.phone,mode,fromLang:myLang,toLang:active.lang,senderName:myProfile?.name||'',senderPhoto:myProfile?.photo||''}});status('Çalıyor…')}
$('audio').onclick=()=>ring('audio');$('video').onclick=()=>ring('video');function showCall(mode){$('call').classList.remove('hidden');$('peer').textContent=active?.name||fmt(callState?.peer);$('call').classList.toggle('audioMode',mode==='audio')}
async function media(){if(stream)return;stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:callState.mode==='video'?{facingMode:'user'}:false});$('local').srcObject=stream}
async function makePeer(){await media();pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.ontrack=e=>$('remote').srcObject=e.streams[0];pc.onicecandidate=e=>{if(e.candidate&&callChan)callChan.send({type:'broadcast',event:'ice',payload:{id:callState.id,from:myNo,candidate:e.candidate.toJSON()}})}}
async function joinCall(){if(callChan)return;callChan=sb.channel('test-call-v4:'+callState.id);callChan.on('broadcast',{event:'offer'},async({payload})=>{if(callState.role!=='callee')return;await makePeer();await pc.setRemoteDescription(payload.offer);const a=await pc.createAnswer();await pc.setLocalDescription(a);await callChan.send({type:'broadcast',event:'answer',payload:{id:callState.id,answer:pc.localDescription.toJSON()}})});callChan.on('broadcast',{event:'answer'},async({payload})=>{if(callState.role==='caller'&&pc)await pc.setRemoteDescription(payload.answer)});callChan.on('broadcast',{event:'ice'},async({payload})=>{if(payload.from!==myNo&&pc)try{await pc.addIceCandidate(payload.candidate)}catch{}});callChan.on('broadcast',{event:'hangup'},()=>endCall());callChan.on('broadcast',{event:'caption'},({payload})=>{if(payload.from!==myNo)addSub(payload.translated||payload.original)});await callChan.subscribe()}
async function offer(){await makePeer();const o=await pc.createOffer();await pc.setLocalDescription(o);await callChan.send({type:'broadcast',event:'offer',payload:{id:callState.id,offer:pc.localDescription.toJSON()}});startCaptions()}
$('accept').onclick=async()=>{if(!incoming)return;active=contacts.find(c=>c.phone===incoming.from)||{name:incoming.senderName||fmt(incoming.from),phone:incoming.from,lang:incoming.fromLang||'auto',photo:incoming.senderPhoto||''};callState={id:incoming.id,role:'callee',peer:incoming.from,mode:incoming.mode};$('incoming').classList.add('hidden');showCall(incoming.mode);await media();await joinCall();await sb.channel('test-phone-v4:'+key(incoming.from)).send({type:'broadcast',event:'accept',payload:{id:incoming.id}});incoming=null;startCaptions()};$('decline').onclick=async()=>{if(!incoming)return;await sb.channel('test-phone-v4:'+key(incoming.from)).send({type:'broadcast',event:'decline',payload:{id:incoming.id}});$('incoming').classList.add('hidden');incoming=null};$('hang').onclick=async()=>{if(callChan)await callChan.send({type:'broadcast',event:'hangup',payload:{id:callState?.id}});endCall()};
function endCall(){try{pc?.close()}catch{}pc=null;stream?.getTracks().forEach(t=>t.stop());stream=null;$('remote').srcObject=null;$('local').srcObject=null;if(callChan)sb.removeChannel(callChan);callChan=null;callState=null;$('call').classList.add('hidden');stopCaptions();status('Hazır')}
$('mic').onclick=()=>{const t=stream?.getAudioTracks()?.[0];if(t)t.enabled=!t.enabled};$('cam').onclick=()=>{const t=stream?.getVideoTracks()?.[0];if(t)t.enabled=!t.enabled};
function addSub(t){const d=document.createElement('div');d.className='subline';d.textContent=t;$('subs').appendChild(d);setTimeout(()=>d.remove(),6500)}
function startCaptions(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR||captionRec)return;captionRec=new SR();captionRec.lang=myLang;captionRec.continuous=true;captionRec.interimResults=false;captionRec.onresult=async e=>{const text=e.results[e.results.length-1]?.[0]?.transcript||'';if(!text||!active?.lang||active.lang==='auto')return;const translated=await translate(text,myLang,active.lang);callChan?.send({type:'broadcast',event:'caption',payload:{from:myNo,original:text,translated}})};captionRec.onend=()=>{if(callState)try{captionRec.start()}catch{}};try{captionRec.start()}catch{captionRec=null}}
function stopCaptions(){try{captionRec?.stop()}catch{}captionRec=null}
fillCountries();fillLanguages();if(myNo&&myProfile)showHome();else showPhone();