(()=>{
const $=id=>document.getElementById(id),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const toast=t=>{const s=$('status');if(s)s.textContent=t};
const profile=()=>{try{return JSON.parse(localStorage.getItem('italky_test_profile_v4')||'{}')}catch{return{}}};
const phoneKey=()=>profile().phone||localStorage.getItem('italky_test_phone_v4')||'guest';
const callKey=()=>`italky_test_calls_v5_${String(phoneKey()).replace(/\D/g,'')}`;
let currentPhone='',selection=false,selected=new Set();
function contacts(){try{return JSON.parse(localStorage.getItem('italky_test_contacts_v4')||'[]')}catch{return[]}}
function currentContact(){const list=contacts();if(currentPhone)return list.find(x=>x.phone===currentPhone)||null;const name=$('chatName')?.textContent?.trim();return list.find(x=>(x.name||x.phone)===name)||null}
function msgKey(phone){const a=String(phoneKey()).replace(/\D/g,''),b=String(phone||'').replace(/\D/g,'');return `italky_test_msgs_v4_${a}_${b}`}
function getMsgs(phone){try{return JSON.parse(localStorage.getItem(msgKey(phone))||'[]')}catch{return[]}}
function putMsgs(phone,a){localStorage.setItem(msgKey(phone),JSON.stringify(a))}
function getCalls(){try{return JSON.parse(localStorage.getItem(callKey())||'[]')}catch{return[]}}
function addCall(type,name,number,status='Arandı'){const a=getCalls();a.unshift({type,name:name||number||'Bilinmeyen',number:number||'',status,at:Date.now()});localStorage.setItem(callKey(),JSON.stringify(a.slice(0,100)));renderCalls()}
function renderCalls(){const p=$('calls');if(!p)return;const a=getCalls();p.innerHTML=a.length?a.map(c=>`<button class="row callHistoryRow"><div class="avatar">${c.type==='video'?'▣':'☎'}</div><div class="rowBody"><div class="rowTop"><strong>${esc(c.name)}</strong><span class="time">${new Date(c.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></div><div class="sub">${c.status} · ${c.type==='video'?'Görüntülü':'Sesli'}${c.number?' · '+esc(c.number):''}</div></div></button>`).join(''):`<div class="empty"><h3>Henüz arama yok</h3><p>Sesli ve görüntülü aramalar burada görünecek.</p></div>`}
function currentPeer(){const c=currentContact();return{name:$('chatName')?.textContent||$('incomingName')?.textContent||c?.name||'',number:c?.phone||$('incomingNo')?.textContent||''}}
function ensureSearch(){if($('v5Overlay'))return;const d=document.createElement('div');d.id='v5Overlay';d.style.cssText='position:absolute;inset:0;z-index:80;background:#fff;display:none;flex-direction:column';d.innerHTML=`<div style="height:58px;background:linear-gradient(135deg,#071b3a,#0a2b57);color:white;display:flex;align-items:center;gap:8px;padding:0 10px"><button id="v5Back" class="svgBtn" aria-label="Geri">‹</button><input id="v5Search" placeholder="Sohbetlerde ara…" style="flex:1;height:38px;border:0;border-radius:19px;padding:0 14px;outline:0"><button id="v5Close" class="svgBtn">×</button></div><div id="v5Results" style="overflow:auto;flex:1;background:white"></div>`;q('.app')?.appendChild(d);$('v5Back').onclick=$('v5Close').onclick=()=>d.style.display='none';$('v5Search').oninput=renderSearch}
function renderSearch(){const term=($('v5Search')?.value||'').toLocaleLowerCase('tr');const rows=qa('#chats .row,#contacts .row');const seen=new Set();$('v5Results').innerHTML=rows.map(r=>{const t=r.innerText.trim();if(!t||seen.has(t)||!t.toLocaleLowerCase('tr').includes(term))return'';seen.add(t);return `<div class="row"><div class="avatar">⌕</div><div class="rowBody"><div class="rowTop"><strong>${esc(t.split('\n')[0])}</strong></div><div class="sub">${esc(t.split('\n').slice(1).join(' · '))}</div></div></div>`}).join('')||'<div class="empty"><h3>Sonuç yok</h3></div>'}
function openSearch(){ensureSearch();$('v5Overlay').style.display='flex';$('v5Search').value='';renderSearch();setTimeout(()=>$('v5Search').focus(),50)}
function ensureLanguage(){if($('langModal'))return;const d=document.createElement('div');d.id='langModal';d.className='langModal';const source=$('myLang');d.innerHTML=`<div class="langCard"><h3>Benim dilim</h3><p>Sen kendi dilini seçersin. Karşı taraf da kendi profilinde kendi dilini seçer. iTalky mesajları otomatik çevirir.</p><select id="settingsLang"></select><button class="saveLang" id="saveLang">Dili kaydet</button><button class="cancelLang" id="cancelLang">Vazgeç</button></div>`;q('.app')?.appendChild(d);if(source)$('settingsLang').innerHTML=source.innerHTML;$('cancelLang').onclick=()=>d.classList.remove('show');d.onclick=e=>{if(e.target===d)d.classList.remove('show')};$('saveLang').onclick=()=>{const lang=$('settingsLang').value||'tr';localStorage.setItem('italky_test_lang_v4',lang);const p=profile();p.lang=lang;localStorage.setItem('italky_test_profile_v4',JSON.stringify(p));if(source)source.value=lang;d.classList.remove('show');toast('Dil güncellendi');setTimeout(()=>location.reload(),280)}}
function openLanguage(){ensureLanguage();$('settingsLang').value=localStorage.getItem('italky_test_lang_v4')||profile().lang||'tr';$('langModal').classList.add('show')}
function ensureMenu(){let m=$('v5Menu');if(m)return m;m=document.createElement('div');m.id='v5Menu';m.className='iTalkyMenu';m.innerHTML='<button data-v5="profile">Profil</button><button data-v5="language">Dil</button><button data-v5="number">Telefon numaram</button><button data-v5="calls">Arama geçmişi</button><button data-v5="select">Mesaj seç</button><button data-v5="clearChat">Sohbeti temizle</button><button data-v5="reset">Test verilerini temizle</button>';q('.app')?.appendChild(m);m.onclick=e=>{const a=e.target.closest('[data-v5]')?.dataset.v5;if(!a)return;m.style.display='none';if(a==='profile'){const p=profile();alert(`Ad: ${p.name||'-'}\nTelefon: ${p.phone||'-'}\nDil: ${p.lang||'-'}`)}else if(a==='language')openLanguage();else if(a==='number')alert(phoneKey());else if(a==='calls')q('[data-tab="calls"]')?.click();else if(a==='select')startSelection();else if(a==='clearChat')clearChat();else if(a==='reset'&&confirm('Bu cihazdaki test mesajları, kişiler ve profil silinsin mi?')){Object.keys(localStorage).filter(k=>k.startsWith('italky_test_')).forEach(k=>localStorage.removeItem(k));location.reload()}};return m}
function toggleMenu(){const m=ensureMenu();m.style.display=m.style.display==='block'?'none':'block'}
function ensureSelectionBar(){if($('selectionBar'))return;const b=document.createElement('div');b.id='selectionBar';b.className='selectionBar';b.innerHTML='<button id="selectionClose">‹</button><div class="count" id="selectionCount">0 seçildi</div><button id="selectionAll" title="Tümünü seç">☑</button><button id="selectionDelete" title="Sil">⌫</button>';q('.chat')?.appendChild(b);$('selectionClose').onclick=endSelection;$('selectionAll').onclick=()=>{selected=new Set(qa('#messages .bubble').map((_,i)=>i));paintSelection()};$('selectionDelete').onclick=deleteSelected}
function startSelection(){if(!currentContact()){toast('Önce bir sohbet aç');return}ensureSelectionBar();selection=true;selected.clear();$('selectionBar').classList.add('show');paintSelection();toast('Silmek istediğin mesajlara dokun')}
function endSelection(){selection=false;selected.clear();$('selectionBar')?.classList.remove('show');qa('#messages .bubble').forEach(x=>x.classList.remove('msg-selected'))}
function paintSelection(){qa('#messages .bubble').forEach((b,i)=>b.classList.toggle('msg-selected',selected.has(i)));if($('selectionCount'))$('selectionCount').textContent=`${selected.size} seçildi`}
function deleteSelected(){const c=currentContact();if(!c||!selected.size)return;if(!confirm(`${selected.size} mesaj silinsin mi?`))return;const a=getMsgs(c.phone).filter((_,i)=>!selected.has(i));putMsgs(c.phone,a);endSelection();location.reload()}
function clearChat(){const c=currentContact();if(!c){toast('Önce bir sohbet aç');return}if(confirm(`${c.name||c.phone} sohbetindeki tüm mesajlar silinsin mi?`)){localStorage.removeItem(msgKey(c.phone));location.reload()}}
function bindMessageSelection(){const box=$('messages');if(!box||box.dataset.selectBound)return;box.dataset.selectBound='1';box.addEventListener('click',e=>{if(!selection)return;const bubble=e.target.closest('.bubble');if(!bubble)return;const list=qa('#messages .bubble'),i=list.indexOf(bubble);if(i<0)return;selected.has(i)?selected.delete(i):selected.add(i);paintSelection();e.preventDefault();e.stopPropagation()},true);let timer=0;box.addEventListener('pointerdown',e=>{const bubble=e.target.closest('.bubble');if(!bubble)return;timer=setTimeout(()=>{if(!selection)startSelection();const list=qa('#messages .bubble'),i=list.indexOf(bubble);if(i>=0){selected.add(i);paintSelection()}},600)});['pointerup','pointercancel','pointermove'].forEach(ev=>box.addEventListener(ev,()=>clearTimeout(timer)))}
function emojiPicker(){let p=$('emojiPickerV5');if(!p){p=document.createElement('div');p.id='emojiPickerV5';p.style.cssText='position:absolute;left:10px;bottom:62px;z-index:70;background:white;border-radius:14px;box-shadow:0 3px 15px #0003;padding:10px;display:none;max-width:290px';p.innerHTML=['😀','😂','😍','🥰','😎','👍','🙏','❤️','🔥','👏','🎉','😢','😡','🤔','😉','😘','👌','💯'].map(x=>`<button style="border:0;background:white;font-size:25px;padding:6px">${x}</button>`).join('');q('.chat')?.appendChild(p);p.onclick=e=>{if(e.target.tagName!=='BUTTON')return;const i=$('msg');i.value+=e.target.textContent;i.dispatchEvent(new Event('input',{bubbles:true}));i.focus()}}p.style.display=p.style.display==='block'?'none':'block'}
function bindRows(){qa('#chats .row,#contacts .row').forEach(r=>{if(r.dataset.phone&&!r.dataset.phoneTrack){r.dataset.phoneTrack='1';r.addEventListener('click',()=>{currentPhone=r.dataset.phone},{passive:true})}})}
function bindSkinButtons(){const acts=qa('.waActions .svgBtn');if(acts[0]&&!acts[0].dataset.bound){acts[0].dataset.bound='1';acts[0].onclick=openSearch}if(acts[1]&&!acts[1].dataset.bound){acts[1].dataset.bound='1';acts[1].onclick=toggleMenu}const mini=qa('.waInputShell .mini');if(mini[0]&&!mini[0].dataset.bound){mini[0].dataset.bound='1';mini[0].onclick=emojiPicker}const more=q('.moreChat');if(more&&!more.dataset.bound){more.dataset.bound='1';more.onclick=toggleMenu}bindRows();bindMessageSelection()}
function bindCalls(){const a=$('audio'),v=$('video'),ac=$('accept'),dc=$('decline'),h=$('hang'),mic=$('mic'),cam=$('cam');if(a&&!a.dataset.log){a.dataset.log='1';a.addEventListener('click',()=>{const p=currentPeer();addCall('audio',p.name,p.number,'Giden arama')},{capture:true})}if(v&&!v.dataset.log){v.dataset.log='1';v.addEventListener('click',()=>{const p=currentPeer();addCall('video',p.name,p.number,'Giden arama')},{capture:true})}if(ac&&!ac.dataset.log){ac.dataset.log='1';ac.addEventListener('click',()=>{const p=currentPeer();addCall($('incomingMode')?.textContent?.includes('Görüntülü')?'video':'audio',p.name,p.number,'Gelen arama · cevaplandı')},{capture:true})}if(dc&&!dc.dataset.log){dc.dataset.log='1';dc.addEventListener('click',()=>{const p=currentPeer();addCall($('incomingMode')?.textContent?.includes('Görüntülü')?'video':'audio',p.name,p.number,'Gelen arama · reddedildi')},{capture:true})}if(h&&!h.dataset.ui){h.dataset.ui='1';h.addEventListener('click',()=>toast('Arama sonlandırıldı'))}if(mic&&!mic.dataset.ui){mic.dataset.ui='1';mic.addEventListener('click',()=>{mic.classList.toggle('off');toast(mic.classList.contains('off')?'Mikrofon kapalı':'Mikrofon açık')})}if(cam&&!cam.dataset.ui){cam.dataset.ui='1';cam.addEventListener('click',()=>{cam.classList.toggle('off');toast(cam.classList.contains('off')?'Kamera kapalı':'Kamera açık')})}}
function rebrand(){document.title='iTalky';qa('.waTitle,.brand').forEach(x=>{if(x.textContent!=='iTalky')x.textContent='iTalky'});qa('*').forEach(el=>{if(el.childNodes.length===1&&el.firstChild?.nodeType===3&&/italkyAI/i.test(el.textContent||''))el.textContent=(el.textContent||'').replace(/italkyAI/gi,'iTalky')})}
function init(){rebrand();renderCalls();bindSkinButtons();bindCalls();ensureLanguage();const obs=new MutationObserver(()=>{bindSkinButtons();bindCalls()});obs.observe(document.body,{subtree:true,childList:true});document.addEventListener('click',e=>{if($('v5Menu')?.style.display==='block'&&!e.target.closest('#v5Menu')&&!e.target.closest('.waActions')&&!e.target.closest('.moreChat'))$('v5Menu').style.display='none'});toast('Hazır')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setTimeout(init,700);
})();